### ISSUE TITLE
Windows: Duplication file shown 100% match,  but actually not

### ISSUE THREAD

**Issue by persona2007** [theophanemayaud/video-simili-duplicate-cleaner#74] opened 2022-05-27 00:30 UTC
it happen for file that having partly or non English word, in the same folder. Scanner will show 100% match with similar thumbnail and properties.

**Comment by theophanemayaud** [comment] 2022-05-28 22:21
Hello, oh I haven't tested non English names, do you have examples of names that are problematic ? 
I believe this might come from how the sub-library being uses, ffmpeg, handles names, but I could see what can be done

**Comment by persona2007** [comment] 2022-05-30 03:04
as todate, did see problem on chinese, korean, japan alphabet. 
Example : x - represent non english aphabet, a - represent english/roman alphabet, if : 

file name : xxxxx.video @ xxxax.video (a can be anywhere in the full wording) were to compare in the same folder, other videos file that containing xxxxx1.video @ xxxxax1.video will show the same properties and thumbnail as xxxxx.video with SSIM:100%.

**Comment by theophanemayaud** [comment] 2023-01-29 16:18
So I checked this out today, with Chinese characters: 
I named a video (random name because I don't know Chinese) 我不是高.mp4, and named a second, completely different video, 我不是高1.mp4

I put both videos in the same folder, scanned it, but the app doesn't report any duplicates. So I don't seem to have your problem. Do you have any more details I could try to reproduce the bug with ?

**Comment by theophanemayaud** [comment] 2023-03-18 18:25
With no news I'm closing this but feel free to reopen if you have more details :)

**Closed by theophanemayaud** 2023-03-18 18:25 UTC
Labels: bug
