### ISSUE TITLE
cannot delete file in network mounted folder, saying permission problem.

### ISSUE THREAD

**Issue by chchia** [theophanemayaud/video-simili-duplicate-cleaner#97] opened 2023-01-26 16:41 UTC
specific a folder for trash work... but can't delete directly.

**Comment by theophanemayaud** [comment] 2023-01-26 18:06
Hi ! Thanks for the report ! On what operating system are you ? Also, when you manually go to the file and delete it, do you have the permissions ?

**Comment by chchia** [comment] 2023-01-27 07:28
Hi I am using Windows 11 with purchased the software from Microsoft Store.
![image](https://user-images.githubusercontent.com/1291771/215030936-9bbe666b-893b-459a-a142-173f4ccfaeaf.png)

For example if i did not define the trash folder this error will show when i click Trash, left or right result the same
![image](https://user-images.githubusercontent.com/1291771/215031261-83c81814-7084-4d48-bfa5-7c7486b1bdc0.png)

but if i do select folder instead of trash, i can then Trash the file but it result in longer time as the folder was a remote network share.
![image](https://user-images.githubusercontent.com/1291771/215031463-816ac283-133e-435b-8bf6-63cc5e98ba98.png)

i hope you can understand what i say, i think you can simply replicate it by add a folder that remote mounted as network storage, and you should know the problem.

thanks.

**Comment by theophanemayaud** [comment] 2023-01-27 07:32
Ok thanks for all the details ! I’ll try to check this out this weekend and see what might be the cause.

**Comment by chchia** [comment] 2023-01-27 07:36
also could you consider to add auto deletion purely by File age (newer or older)  or by File Zize and ignoring the similarity (i know very dangerous unless user are super confidence about the data to be deleted is correctly marked as similar)

**Comment by theophanemayaud** [comment] 2023-01-29 11:04
Ok so I just checked, and I have exactly the same problem : trash when in network drive doesn't work, except when setting a custom location to move the files to instead of the trash. I'm on windows 10. 
Investigation : 
As per https://superuser.com/questions/160990/put-files-deleted-over-the-network-into-a-windows-trash-can, there is no trash on network drives. Thus, because the app uses a move to trash function, it will never work on systems with no trash, as per https://doc.qt.io/qt-6/qfile.html#moveToTrash it is the expected behavior.

Idea : 
- check if drive has trash, else warn user
- propose option to delete directly

Will keep investigating

**Comment by theophanemayaud** [comment] 2023-01-29 16:04
It doesn't seem straightforward to check if the drive has a trash. Therefore, I simply added in the error message that it could be a reason for failing to move to trash.
I also added the overall setting, instead of moving to trash or moving to a specified folder, to delete outright. If you have lots of files on a network drive, you can enable this as soon as the update is release by microsoft :) 
Closed by 22f366c94b4aec91302c38f3f1a9fb8d5ba47c43

**Closed by theophanemayaud** 2023-01-29 16:04 UTC
Labels: bug, Windows

**Comment by theophanemayaud** [comment] 2023-03-19 23:16
> and please allow to save setting, so that user do not need to add folder and set other setting again every time the program is restarted. ![image](https://user-images.githubusercontent.com/1291771/215035589-13e843b4-44bd-4388-95d6-9cf641c3550c.png)

By the way I'm also tracking this in #101
